# fly.toml app configuration file generated for oxidizer-demo on 2023-06-07T16:35:27-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "oxidizer-demo"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  PRIMARY_REGION = "sjc"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[mounts]
  source="oxidizer_demo_litestack_data"
  destination="/data"